"""
End-to-end tests for the second brain. Each hook runs as a subprocess with a
throwaway DUPE_GUARD_HOME and vault; transcripts are synthetic JSONL in the
shape Claude Code writes. distill talks to a fake `claude` that replies from
files, so the hard cases (EMPTY, bad format, split votes) are reproducible
and cost nothing.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAIN = ROOT / "brain"

FAKE_CLAUDE = textwrap.dedent('''\
    #!/usr/bin/env python3
    import os, sys
    prompt = sys.stdin.read()
    d = os.environ["FAKE_DIR"]
    kind = "stale" if "does the new block make" in prompt else "distill"
    n = 0
    while True:                       # atomic call counter, safe in parallel
        try:
            os.mkdir(os.path.join(d, f"{kind}-call-{n}")); break
        except FileExistsError:
            n += 1
    f = os.path.join(d, f"{kind}-{n}.txt")
    if not os.path.exists(f):
        f = os.path.join(d, f"{kind}-default.txt")
    print(open(f).read() if os.path.exists(f) else "EMPTY")
''')

NOTE = """---
tags: [project]
---

# billing-api

## Architecture

Invoices are generated by a nightly job and stored in Postgres.

## Decisions

- Retries use exponential backoff.

## Related

- [[Payments]]
"""


def line(**kw):
    # compact, the way Claude Code writes its transcripts
    return json.dumps(kw, separators=(",", ":")) + "\n"


def transcript(path, cwd, prompts, sid="s1", extra=()):
    """A synthetic transcript: prompts, assistant replies, an Edit, usage."""
    rows = [line(type="ai-title", aiTitle="Invoice retries")]
    t = 0
    for p in prompts:
        t += 1
        rows.append(line(type="user", cwd=cwd, gitBranch="feature/x", sessionId=sid,
                         timestamp=f"2026-09-20T10:{t:02d}:00Z", message={"role": "user", "content": p}))
        rows.append(line(type="assistant", cwd=cwd, timestamp=f"2026-09-20T10:{t:02d}:30Z",
                         message={"role": "assistant", "usage": {"input_tokens": 10, "output_tokens": 5},
                                  "content": [{"type": "text", "text": "Decided to keep the nightly job because "
                                               "moving invoices to a queue would double the failure modes. " * 2},
                                              {"type": "tool_use", "id": f"t{t}", "name": "Edit",
                                               "input": {"file_path": f"{cwd}/src/invoice.py"}}]}))
    rows.extend(extra)
    Path(path).write_text("".join(rows))


class Brain(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="dupe-guard-brain-"))
        self.home = self.tmp / "home"
        self.vault = self.tmp / "vault"
        self.repo = self.tmp / "billing-api"
        (self.vault / "Projects").mkdir(parents=True)
        (self.vault / "Projects" / "billing-api.md").write_text(NOTE)
        (self.vault / "Concepts").mkdir()
        (self.vault / "Concepts" / "Exponential backoff.md").write_text(
            "# Exponential backoff\n\nRetry delays double each attempt, with jitter, capped at a maximum.\n")
        (self.repo / "src").mkdir(parents=True)
        (self.repo / "src" / "invoice.py").write_text("def total(): return 1\n")
        subprocess.run(["git", "init", "-q"], cwd=self.repo, check=True)
        self.fake = self.tmp / "fake"
        self.fake.mkdir()
        (self.fake / "claude").write_text(FAKE_CLAUDE)
        (self.fake / "claude").chmod(0o755)
        self.env = {**os.environ, "DUPE_GUARD_HOME": str(self.home), "DUPE_GUARD_VAULT": str(self.vault),
                    "DUPE_GUARD_BRAIN": "1", "DUPE_GUARD_CLAUDE": str(self.fake / "claude"),
                    "FAKE_DIR": str(self.fake)}

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def run_py(self, script, payload=None, env=None, args=()):
        r = subprocess.run([sys.executable, str(BRAIN / script), *args],
                           input=json.dumps(payload) if payload is not None else "",
                           capture_output=True, text=True, timeout=60, env=env or self.env)
        self.assertEqual(r.returncode, 0, r.stderr + r.stdout)
        return r.stdout

    def context(self, out):
        return json.loads(out)["hookSpecificOutput"]["additionalContext"] if out.strip() else None

    def end_session(self, prompts, sid="s1", extra=()):
        tp = self.tmp / f"{sid}.jsonl"
        transcript(tp, str(self.repo), prompts, sid, extra)
        self.run_py("session_log.py", {"session_id": sid, "transcript_path": str(tp), "reason": "exit"})
        return tp

    def raw_today(self):
        files = list((self.vault / "Sessions" / "Raw").glob("*.md"))
        return files[0].read_text() if files else ""

    # ------------------------------------------------------------ off by default

    def test_everything_is_off_until_enabled(self):
        env = {k: v for k, v in self.env.items() if k != "DUPE_GUARD_BRAIN"}
        tp = self.tmp / "s.jsonl"
        transcript(tp, str(self.repo), ["please make invoice retries use backoff"] * 3)
        self.run_py("session_log.py", {"session_id": "s", "transcript_path": str(tp)}, env=env)
        self.assertFalse((self.vault / "Sessions").exists())
        self.assertEqual(self.run_py("vault_context.py", {}, env=env), "")
        self.assertEqual(self.run_py("recall.py", {"prompt": "how do exponential backoff retries work here"},
                                     env=env), "")

    # ------------------------------------------------------------- session log

    def test_session_log_records_the_session_and_queues_it(self):
        self.end_session(["make invoice retries use exponential backoff please",
                          "keep the nightly job, do not move invoices to a queue",
                          "and write down why we kept the nightly job"])
        raw = self.raw_today()
        self.assertIn("— billing-api", raw)
        self.assertIn("[[billing-api]]", raw)
        self.assertIn("`feature/x`", raw)
        self.assertIn("src/invoice.py", raw)
        self.assertIn("_Tokens: in=30 out=15", raw)
        queue = [json.loads(l) for l in (self.home / "brain" / "distill-queue.jsonl").read_text().splitlines()]
        self.assertEqual([q["note"] for q in queue], ["billing-api"])

    def test_session_log_is_idempotent(self):
        prompts = ["make invoice retries use exponential backoff please"] * 3
        self.end_session(prompts)
        self.end_session(prompts)
        self.assertEqual(self.raw_today().count("<!-- sid:s1 "), 1)

    def test_session_without_substance_writes_nothing(self):
        self.end_session(["ok", "go ahead"])
        self.assertEqual(self.raw_today(), "")

    # ----------------------------------------------------------- vault context

    def test_vault_context_lists_top_level_folders_by_default(self):
        ctx = self.context(self.run_py("vault_context.py", {}))
        self.assertIn("## Projects", ctx)
        self.assertIn("billing-api", ctx)
        self.assertIn("## Concepts", ctx)

    # ------------------------------------------------------------ search/recall

    def reindex(self):
        self.run_py("ksearch.py", args=["--reindex"])

    def test_default_vault_inside_a_hidden_folder_is_indexed(self):
        # Regression: the indexer skipped any path with a dot-folder ANYWHERE in
        # it, so a vault under, say, ~/.config or ~/.dupe-guard was never indexed.
        env = {**self.env, "DUPE_GUARD_VAULT": str(self.home / "vault")}
        shutil.copytree(self.vault, self.home / "vault")
        self.run_py("ksearch.py", env=env, args=["--reindex"])
        out = json.loads(self.run_py("ksearch.py", env=env, args=["backoff", "--json"]))
        self.assertTrue(any(r["title"] == "Exponential backoff" for r in out["results"]))

    def test_recall_speaks_on_a_subject_and_stays_quiet_otherwise(self):
        self.reindex()
        ctx = self.context(self.run_py("recall.py", {"prompt": "how should exponential backoff work for invoice retries",
                                                     "session_id": "r1"}))
        self.assertIsNotNone(ctx)
        self.assertIn("Exponential backoff", ctx)
        self.assertEqual(self.run_py("recall.py", {"prompt": "ok go ahead", "session_id": "r1"}), "")

    def test_recall_does_not_repeat_itself_in_a_session(self):
        self.reindex()
        p = {"prompt": "how should exponential backoff work for invoice retries", "session_id": "r2"}
        self.assertIsNotNone(self.context(self.run_py("recall.py", p)))
        self.assertIsNone(self.context(self.run_py("recall.py", p)))

    # --------------------------------------------------------------- proposals

    def test_unread_recall_becomes_a_stopword_proposal_and_apply_silences_it(self):
        self.reindex()
        prompt = "how should exponential backoff work for invoice retries"
        ctx = self.context(self.run_py("recall.py", {"prompt": prompt, "session_id": "p1"}))
        injection = line(type="attachment", timestamp="2026-09-20T10:01:10Z",
                         attachment={"type": "hook_additional_context", "hookName": "UserPromptSubmit",
                                     "content": [ctx]})
        tp = self.tmp / "p1.jsonl"
        rows = [line(type="user", cwd=str(self.repo), timestamp="2026-09-20T10:01:00Z",
                     message={"role": "user", "content": prompt}), injection,
                line(type="assistant", timestamp="2026-09-20T10:01:20Z",
                     message={"role": "assistant", "content": [{"type": "text", "text": "Done."}]})]
        tp.write_text("".join(rows))
        out = self.run_py("proposals.py", args=["--generate", str(tp), "p1", "--record"])
        self.assertIn("stopword", out)
        page = self.vault / "Harness Proposals.md"
        text = page.read_text()
        self.assertIn("- [ ] `st-p1-", text)
        # approve every stopword, as the user would in chat or in the editor
        page.write_text(text.replace("- [ ] `st-", "- [x] `st-"))
        self.assertIn("applied", self.run_py("proposals.py", args=["--apply"]))
        self.assertIn("✅ applied", page.read_text())
        self.assertIsNone(self.context(self.run_py("recall.py", {"prompt": prompt, "session_id": "p2"})))

    def test_an_admitted_correction_becomes_a_convention_proposal(self):
        rows = [line(type="user", timestamp="2026-09-20T10:01:00Z",
                     message={"role": "user", "content": "why did you say the job runs hourly? it is nightly"}),
                line(type="assistant", timestamp="2026-09-20T10:01:20Z",
                     message={"role": "assistant", "content": [{"type": "text", "text": "You're right, I made that up."}]})]
        tp = self.tmp / "c1.jsonl"
        tp.write_text("".join(rows))
        out = self.run_py("proposals.py", args=["--generate", str(tp), "c1", str(self.repo)])
        self.assertIn("convention", out)
        self.assertIn("billing-api", out)

    # ----------------------------------------------------------------- distill

    def reply(self, kind, n, text):
        (self.fake / f"{kind}-{n}.txt").write_text(text)

    def queue_one(self):
        self.end_session(["make invoice retries use exponential backoff please",
                          "keep the nightly job, do not move invoices to a queue",
                          "and write down why we kept the nightly job"])

    def note(self):
        return (self.vault / "Projects" / "billing-api.md").read_text()

    def test_distill_dry_run_writes_nothing(self):
        self.queue_one()
        self.reply("distill", 0, "## Kept the nightly job 🔑\n\n- A queue doubles the failure modes.")
        out = self.run_py("distill.py")
        self.assertIn("+## Kept the nightly job 🔑 (2026-09-20)", out)
        self.assertEqual(self.note(), NOTE)

    def test_distill_apply_inserts_before_closing_section_with_the_session_date(self):
        self.queue_one()
        self.reply("distill", 0, "## Kept the nightly job (2026-01-01) 🔑\n\n- A queue doubles the failure modes.")
        self.run_py("distill.py", args=["--apply"])
        note = self.note()
        self.assertIn("## Kept the nightly job 🔑 (2026-09-20)", note)
        self.assertLess(note.index("Kept the nightly job"), note.index("## Related"))
        self.assertIn("<!-- distilled:s1 -->", note)
        self.assertIn("queue empty", self.run_py("distill.py", args=["--apply"]))

    def test_distill_retries_a_malformed_answer_once(self):
        self.queue_one()
        self.reply("distill", 0, "| 2026-09-20 | kept the nightly job |")
        self.reply("distill", 1, "## Kept the nightly job\n\n- reason")
        self.run_py("distill.py", args=["--apply"])
        self.assertIn("## Kept the nightly job (2026-09-20)", self.note())

    def test_distill_gives_up_after_two_malformed_answers(self):
        self.queue_one()
        self.reply("distill", "default", "- just a bullet")
        out = self.run_py("distill.py", args=["--apply"])
        self.assertIn("invalid format after 2 attempts", out)
        self.assertEqual(self.note(), NOTE)

    def test_distill_empty_answer_records_nothing(self):
        self.queue_one()
        self.reply("distill", 0, "EMPTY")
        self.assertIn("nothing new", self.run_py("distill.py", args=["--apply"]))
        self.assertEqual(self.note(), NOTE)

    def test_staleness_needs_a_majority_of_samples(self):
        self.queue_one()
        self.reply("distill", 0, "## Invoices moved to a queue\n\n- The nightly job is gone.")
        # sections seen by the checker: 1 Architecture, 2 Decisions (Related is an index)
        self.reply("stale", 0, "1 | CONTRADICTS | invoices are no longer made by a nightly job\n2 | NO |")
        self.reply("stale", 1, "1 | CONTRADICTS | nightly job replaced\n2 | CONTRADICTS | x")
        self.reply("stale", 2, "1 | NO |\n2 | NO |")
        self.run_py("distill.py", args=["--apply"])
        note = self.note()
        arch = note[note.index("## Architecture"):note.index("## Decisions")]
        dec = note[note.index("## Decisions"):note.index("## Invoices moved")]
        self.assertIn("⚠️ **Superseded by", arch)           # 2 of 3 votes
        self.assertNotIn("Superseded", dec)                 # 1 of 3 votes

    def test_distill_commit_has_no_trailers(self):
        subprocess.run(["git", "init", "-q"], cwd=self.vault, check=True)
        subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "add", "-A"], cwd=self.vault, check=True)
        subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "base"],
                       cwd=self.vault, check=True)
        self.queue_one()
        self.reply("distill", 0, "## Kept the nightly job\n\n- reason")
        env = {**self.env, "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
               "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t"}
        self.run_py("distill.py", env=env, args=["--apply", "--commit"])
        msg = subprocess.run(["git", "log", "-1", "--format=%B"], cwd=self.vault,
                             capture_output=True, text=True).stdout
        self.assertIn("billing-api: distilled from the session of 2026-09-20", msg)
        self.assertNotIn("Co-Authored", msg)


if __name__ == "__main__":
    unittest.main()
